id: P000809
initial_creation_type: ocr
created_at: 5/04/2021
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W2DB4582
  title: ཨར་བྱང་ཆུབ་ཡེ་ཤེས་ཀྱི་གསུང་ཆོས་སྐོར
  volumes:
    324e0c10b45a4e40adcca00b2ff90e4d:
      image_group_id: I1GS88132
      title: ''
      base_file: v001.txt
  author: ''
